kind: pipeline
name: default

steps:
  - name: docker  
    image: plugins/docker
    settings:
        repo: maxkratz/ros2dashing
        tags: opencv
        username:
            from_secret: dockerhub_username
        password:
            from_secret: dockerhub_password
    when:
        branch:
            - opencv