name: Build and push Docker images
on:
  push:
    branches:
      - 'main'
      - 'master'

jobs:
  build-latest:
    runs-on: [ubuntu-24.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build latest
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: maxkratz/ros2dashing:latest
          platforms: linux/amd64

  build-opencv:
    runs-on: [ubuntu-24.04]
    needs: [build-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build OpenCV version
        uses: docker/build-push-action@v5
        with:
          context: ./opencv
          push: true
          tags: maxkratz/ros2dashing:opencv
          platforms: linux/amd64
