name: Build Docker images
on:
  push:
    branches:
      - 'testing/**'
      - 'feature/**'
      - 'hotfix/**'

jobs:
  build-latest:
    runs-on: [ubuntu-24.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build latest
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: maxkratz/ros2dashing:latest
          platforms: linux/amd64

  build-opencv:
    runs-on: [ubuntu-24.04]
    needs: [build-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build OpenCV version
        uses: docker/build-push-action@v5
        with:
          context: ./opencv
          push: false
          tags: maxkratz/ros2dashing:opencv
          platforms: linux/amd64
