name: Build Docker images
on:
  push:
    branches:
      - '!main'
      - 'testing/**'
      - 'feature/**'
      - 'hotfix/**'

jobs:
  build-latest:
    runs-on: [ubuntu-22.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build base
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          tags: maxkratz/ros2dashing:latest
          platforms: linux/amd64

  build-image:
    runs-on: [ubuntu-22.04]
    needs: [build-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build image
        uses: docker/build-push-action@v3
        with:
          context: ./opencv
          push: false
          tags: maxkratz/ros2dashing:opencv
          platforms: linux/amd64
